GET http://localhost:3001/notes/

###
DELETE http://localhost:3001/notes/1

###
POST http://localhost:3001/notes/
Content-Type: application/json

{
  "content": "Amir dai is using phone",
  "important": true
}